nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000'] 
        allow_methods: ['GET', 'POST', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        max_age: 3600
        allow_credentials: true