nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']  # Permet toutes les origines, à ajuster en production
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/': ~  # Autorise toutes les routes commençant par /api
