nelmio_cors:
    defaults:
<<<<<<< HEAD
        allow_origin: ['*']   
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']  
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With'] 
        max_age: 3600  
        allow_credentials: true  
=======
        allow_origin: ['http://localhost:3000']
        allow_methods: ['GET', 'POST', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
        allow_credentials: true
>>>>>>> b674ca31ac183ecc96aa6fe014c90eabab0fa299
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'POST', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            allow_credentials: true
