nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']   
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']  
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With'] 
        max_age: 3600  
        allow_credentials: true  
    paths:
        '^/api/': ~  
