security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_database:
            entity:
                class: App\Entity\User
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            # Si tu veux l'API accessible sans authentification pour certaines routes
            pattern: ^/api/
            stateless: true  # Pas de session, stateless pour l'API
            provider: users_in_database
            security: false  # Désactive l'authentification pour certaines routes, comme les "GET" publiques

        main:
            lazy: true
            provider: users_in_database

    # Accès aux routes
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Permet l'accès anonyme à /api/login
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }          # Permet l'accès anonyme à toutes les routes sous /api
